"""
RoutingRuleSourceAdmin — rule source CRUD + preview/import for routing-admin.
Installed by routing-installer Stage 2E.
Extends RoutingUpstreamAdmin (Stage 2B) and adds /rule-sources/* routes.
__init__.py is patched by install-routing.sh to import this class.
"""
from __future__ import annotations

import re

from flask import abort, flash, g, redirect, render_template, request
from flask_classful import route
from hiddifypanel.auth import login_required
from hiddifypanel.database import db
from hiddifypanel.models import Role

from .RoutingUpstreamAdmin import RoutingAdmin as _BaseUpstreamAdmin

_NAME_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}$")
_VALID_SOURCE_TYPES = {"text", "external_url", "local_file"}
_VALID_FAMILIES = {"domain", "subnet"}
_VALID_POLICIES = {"to_upstream", "direct_ru", "block"}
_VALID_FORMATS = {"auto", "plain_text", "sing_box_source_json", "sing_box_binary_srs"}


def _validate_source(
    name: str,
    source_type: str,
    rule_family: str,
    source_format: str,
    outbound_policy: str,
    url: str,
    local_path: str,
) -> str | None:
    if not name or not _NAME_RE.match(name):
        return "Имя источника: только латинские буквы, цифры, дефис, подчёркивание (1–64 символа)."
    if source_type not in _VALID_SOURCE_TYPES:
        return "Недопустимый тип источника."
    if rule_family not in _VALID_FAMILIES:
        return "Недопустимое семейство правил."
    if source_format not in _VALID_FORMATS:
        return "Недопустимый формат источника."
    if outbound_policy not in _VALID_POLICIES:
        return "Недопустимая политика outbound."
    if source_type == "external_url":
        u = url.strip()
        if not u:
            return "Для типа 'Внешний URL' укажите URL."
        if not (u.startswith("http://") or u.startswith("https://")):
            return "URL должен начинаться с http:// или https://"
    if source_type == "local_file":
        if not local_path.strip():
            return "Для типа 'Локальный файл' укажите путь."
    return None


def _parse_form() -> dict:
    return {
        "name":            request.form.get("name", "").strip(),
        "label":           request.form.get("label", "").strip(),
        "enabled":         request.form.get("enabled") == "1",
        "source_type":     request.form.get("source_type", "text").strip(),
        "rule_family":     request.form.get("rule_family", "domain").strip(),
        "source_format":   request.form.get("source_format", "auto").strip(),
        "outbound_policy": request.form.get("outbound_policy", "direct_ru").strip(),
        "content_text":    request.form.get("content_text", ""),
        "url":             request.form.get("url", "").strip(),
        "local_path":      request.form.get("local_path", "").strip(),
    }


def _sources_url() -> str:
    return f"/{g.proxy_path}/admin/routing-admin/rule-sources/"


def _routing_admin_url() -> str:
    return f"/{g.proxy_path}/admin/routing-admin/"


class RoutingAdmin(_BaseUpstreamAdmin):
    """RoutingAdmin extended with rule source CRUD — installed by routing-installer Stage 2E."""

    route_base = "/routing-admin"
    decorators = [login_required(roles={Role.super_admin})]

    def _default_section(self):
        return "routing"

    def post(self):
        # BusinessAdmin.save() calls hiddify.check_need_reset() which may flash
        # a "Click [Apply configuration] to apply" banner when routing hconfig keys
        # (commercial_routing_enable, commercial_apply_to_xray, etc.) change.
        # That banner triggers apply_configs.sh which makes external network calls
        # and hangs on restricted VMs. For routing, commercial-routing-apply already
        # handles xray-router reconfiguration — apply_configs.sh is NOT needed here.
        # We call super().post() then strip the apply-redirect flash from the session.
        from flask import session
        result = super().post()
        # Remove any flash messages that contain an "apply_configs" link — these are
        # the green banners generated by flash_config_success(ApplyMode.apply_config).
        flashes = session.get("_flashes", [])
        session["_flashes"] = [
            (cat, msg) for cat, msg in flashes
            if "apply_configs" not in msg and "admin.config.apply_configs" not in msg
        ]
        return result

    # ── List ──────────────────────────────────────────────────────────────────

    @route("/rule-sources/", methods=["GET"])
    def rule_source_list(self):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        sources = CommercialRoutingRuleSource.get_all_ordered()
        return render_template(
            "routing-rule-source.html",
            sources=sources,
            source=None,
            source_id=None,
            action="list",
            preview_result=None,
            routing_admin_url=_routing_admin_url(),
            sources_url=_sources_url(),
        )

    # ── Add ───────────────────────────────────────────────────────────────────

    @route("/rule-sources/add/", methods=["GET", "POST"])
    def rule_source_add(self):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        if request.method == "POST":
            data = _parse_form()
            err = _validate_source(
                data["name"], data["source_type"], data["rule_family"],
                data["source_format"], data["outbound_policy"],
                data["url"], data["local_path"],
            )
            if err:
                flash(err, "danger")
                return render_template(
                    "routing-rule-source.html",
                    sources=None, source=data, source_id=None, action="add",
                    preview_result=None,
                    routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
                )
            if CommercialRoutingRuleSource.query.filter_by(name=data["name"]).first():
                flash(f"Источник с именем '{data['name']}' уже существует.", "danger")
                return render_template(
                    "routing-rule-source.html",
                    sources=None, source=data, source_id=None, action="add",
                    preview_result=None,
                    routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
                )
            src = CommercialRoutingRuleSource(**data)
            db.session.add(src)
            db.session.commit()
            flash(f"Источник «{src.label or src.name}» добавлен.", "success")
            return redirect(_sources_url())

        return render_template(
            "routing-rule-source.html",
            sources=None, source=None, source_id=None, action="add",
            preview_result=None,
            routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
        )

    # ── Edit ──────────────────────────────────────────────────────────────────

    @route("/rule-sources/<int:source_id>/edit/", methods=["GET", "POST"])
    def rule_source_edit(self, source_id: int):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        src = db.session.get(CommercialRoutingRuleSource, source_id)
        if src is None:
            abort(404)

        if request.method == "POST":
            data = _parse_form()
            err = _validate_source(
                data["name"], data["source_type"], data["rule_family"],
                data["source_format"], data["outbound_policy"],
                data["url"], data["local_path"],
            )
            if err:
                flash(err, "danger")
                return render_template(
                    "routing-rule-source.html",
                    sources=None, source=data, source_id=source_id, action="edit",
                    preview_result=None,
                    routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
                )
            conflict = CommercialRoutingRuleSource.query.filter(
                CommercialRoutingRuleSource.name == data["name"],
                CommercialRoutingRuleSource.id != source_id,
            ).first()
            if conflict:
                flash(f"Источник с именем '{data['name']}' уже существует.", "danger")
                return render_template(
                    "routing-rule-source.html",
                    sources=None, source=data, source_id=source_id, action="edit",
                    preview_result=None,
                    routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
                )
            for k, v in data.items():
                setattr(src, k, v)
            db.session.commit()
            flash(f"Источник «{src.label or src.name}» сохранён.", "success")
            return redirect(_sources_url())

        return render_template(
            "routing-rule-source.html",
            sources=None, source=src, source_id=source_id, action="edit",
            preview_result=None,
            routing_admin_url=_routing_admin_url(), sources_url=_sources_url(),
        )

    # ── Delete ────────────────────────────────────────────────────────────────

    @route("/rule-sources/<int:source_id>/delete/", methods=["POST"])
    def rule_source_delete(self, source_id: int):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        from hiddifypanel.models.commercial_routing_custom_rule import (
            CommercialRoutingCustomRule,
        )
        src = db.session.get(CommercialRoutingRuleSource, source_id)
        if src is None:
            abort(404)
        label = src.label or src.name
        # Delete all rules imported from this source before removing it
        deleted_rules = CommercialRoutingCustomRule.query.filter_by(
            source_id=source_id
        ).delete()
        db.session.delete(src)
        db.session.commit()
        flash(
            f"Источник «{label}» удалён вместе с {deleted_rules} правилами. "
            "Нажмите «Применить xray-router» для обновления конфига.",
            "success",
        )
        return redirect(_sources_url())

    # ── Toggle ────────────────────────────────────────────────────────────────

    @route("/rule-sources/<int:source_id>/toggle/", methods=["POST"])
    def rule_source_toggle(self, source_id: int):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        from hiddifypanel.models.commercial_routing_custom_rule import (
            CommercialRoutingCustomRule,
        )
        src = db.session.get(CommercialRoutingRuleSource, source_id)
        if src is None:
            abort(404)
        src.enabled = not src.enabled
        # Sync enabled state to all rules imported from this source
        affected = CommercialRoutingCustomRule.query.filter_by(
            source_id=source_id
        ).update({"enabled": src.enabled})
        db.session.commit()
        state = "включён" if src.enabled else "выключен"
        flash(
            f"Источник «{src.label or src.name}» {state}. "
            f"Правил {'активировано' if src.enabled else 'деактивировано'}: {affected}. "
            "Нажмите «Применить xray-router» для обновления конфига.",
            "success",
        )
        return redirect(_sources_url())

    # ── Preview ───────────────────────────────────────────────────────────────

    @route("/rule-sources/<int:source_id>/preview/", methods=["POST"])
    def rule_source_preview(self, source_id: int):
        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        from hiddifypanel.hutils.commercial_routing_source_parser import preview_source

        src = db.session.get(CommercialRoutingRuleSource, source_id)
        if src is None:
            abort(404)

        parse_result, fetch_err = preview_source(src)

        preview_result = {
            "fetch_error": fetch_err,
            "detected_format": parse_result.detected_format,
            "rules_count": len(parse_result.rules),
            "duplicates": parse_result.duplicates,
            "errors_count": len(parse_result.errors),
            "lines_total": parse_result.lines_total,
            "lines_skipped": parse_result.lines_skipped,
            "sample_rules": [
                {"rule_type": r.rule_type, "normalized_value": r.normalized_value}
                for r in parse_result.rules[:20]
            ],
            "sample_errors": parse_result.errors[:20],
            "sample_warnings": parse_result.warnings[:10],
        }

        return render_template(
            "routing-rule-source.html",
            sources=None,
            source=src,
            source_id=source_id,
            action="preview",
            preview_result=preview_result,
            routing_admin_url=_routing_admin_url(),
            sources_url=_sources_url(),
        )

    # ── Apply router-core config ──────────────────────────────────────────────

    @route("/rule-sources/apply-router/", methods=["POST"])
    def apply_router(self):
        import subprocess
        try:
            proc = subprocess.run(
                ["sudo", "-n", "/opt/hiddify-manager/common/commander.py",
                 "commercial-routing-apply"],
                capture_output=True,
                text=True,
                timeout=60,
            )
            if proc.returncode == 0:
                flash("xray-router конфиг применён успешно.", "success")
            else:
                msg = (proc.stderr or proc.stdout or "unknown error").strip()[:300]
                flash(f"Ошибка apply: {msg}", "danger")
        except subprocess.TimeoutExpired:
            flash("Применение xray-router заняло более 60 секунд — проверьте статус вручную.", "warning")
        except Exception as exc:
            flash(f"Ошибка apply: {exc}", "danger")
        return redirect(_sources_url())

    # ── Import ────────────────────────────────────────────────────────────────

    @route("/rule-sources/<int:source_id>/import/", methods=["POST"])
    def rule_source_import(self, source_id: int):
        from datetime import datetime

        from hiddifypanel.models.commercial_routing_rule_source import (
            CommercialRoutingRuleSource,
        )
        from hiddifypanel.hutils.commercial_routing_source_parser import import_source

        src = db.session.get(CommercialRoutingRuleSource, source_id)
        if src is None:
            abort(404)

        inserted, skipped, err = import_source(src)

        if err:
            src.last_status = "error"
            src.last_error = err
            src.last_fetched_at = datetime.utcnow()
            db.session.commit()
            flash(f"Ошибка импорта «{src.label or src.name}»: {err}", "danger")
            return redirect(_sources_url())

        src.last_status = "ok"
        src.last_error = None
        src.last_fetched_at = datetime.utcnow()
        src.rules_count = inserted + skipped
        db.session.commit()
        flash(
            f"Источник «{src.label or src.name}»: "
            f"добавлено {inserted}, пропущено дублей {skipped}. "
            "Нажмите «Применить» для обновления конфига xray-router.",
            "success",
        )
        return redirect(_sources_url())
